### ISSUE TITLE
Automatic fallback to static libdav1d build if initial pkg-config probe fails?

### ISSUE THREAD

**Issue by philn** [rust-av/dav1d-rs#26]
Setting `RUSTFLAGS` seems more like a workaround. Would it be acceptable to automatically build libdav1d if it's not found on the host system?

**Comment by sdroege** [comment]
Using cargo features for this is also suboptimal as dav1d is going to be a dependency somewhere down your dependency tree and you can't directly enable that feature from the top-level crate (especially not via cargo commandline arguments).

IMHO the best approach forward here would be what other crates are doing
- By default: If dav1d found via pkg-config, use that or build otherwise
- Separate environment variables for forcing pkg-config-only and for forcing internal build only

**Comment by lu-zero** [comment]
Having this kind of logic using env variables is a little concerning, but if we really want to go that path would be probably better to have something along the lines of `BUILD_CRATE_WITH_PKG_CONFIG=dav1d:{auto,always,never}` and maybe factorize the logic so it can be reused across all the crates that might need this. (I have about 4-5 crates of bindings directly and I can think of many more).

**Comment by sdroege** [comment]
As this is environment variables, it will probably be easier to handle for users of this if there's a separate environment variable per library/crate. Doesn't prevent you from handling it generically in a single place :)

> Having this kind of logic using env variables is a little concerning

Indeed but it's the best choice we have available here unfortunately. cargo features don't have the required semantics for build-time configurations somewhere in the dependency tree, and cargo is generally not well-designed for such things in general.

**Comment by sdroege** [comment]
@gdesmott What's the status of your work? Maybe open a PR so that more people can comment on the approach :)

**Comment by gdesmott** [comment]
I have loads of patches I'd need to get merged into `metadeps` first. I contacted the maintainer who agreed to make me co-maintainer as he's not really active atm but didn't heard from him since.
